# Generated by Django 4.1.5 on 2023-02-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='starts_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
