# Generated by Django 4.1.5 on 2023-02-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_collection_active_collection_ends_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='ends_at',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='starts_from',
            new_name='start_date',
        ),
    ]
