# Generated by Django 4.1.5 on 2023-02-01 11:43

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.CharField(choices=[('Left', 'LEFT'), ('Right', 'RIGHT'), ('Center', 'CENTER')], default=products.models.PositionChoice['CENTER'], max_length=255),
        ),
    ]
