# Generated by Django 4.1.5 on 2023-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_color_remove_product_size_productsize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='null', upload_to='collection_banner/'),
            preserve_default=False,
        ),
    ]
